package uk.gov.communities.prsdb.webapp.models.viewModels.emailModels

interface EmailTemplateModel {
    val template: EmailTemplate

    fun toHashMap(): HashMap<String, String>
}

enum class EmailTemplate {
    LOCAL_COUNCIL_INVITATION_EMAIL,
    LOCAL_COUNCIL_INVITATION_CANCELLATION_EMAIL,
    LOCAL_COUNCIL_ADMIN_INVITATION_EMAIL,
    LANDLORD_REGISTRATION_CONFIRMATION_EMAIL,
    PROPERTY_REGISTRATION_CONFIRMATION,
    PROPERTY_DEREGISTRATION_CONFIRMATION,
    PROPERTY_DEREGISTRATION_INVITEE_CANCELLATION,
    LANDLORD_NO_PROPERTIES_DEREGISTRATION_CONFIRMATION,
    LANDLORD_WITH_PROPERTIES_DEREGISTRATION_CONFIRMATION,
    VIRUS_SCAN_UNSUCCESSFUL,
    PROPERTY_UPDATE_CONFIRMATION,
    INDIVIDUAL_LANDLORD_UPDATE_CONFIRMATION,
    BETA_FEEDBACK_EMAIL,
    COMPLIANCE_UPDATED_CONFIRMATION_EMAIL,
    JOINT_LANDLORD_COMPLIANCE_UPDATED_CONFIRMATION_EMAIL,
    COMPLIANCE_EXPIRED_OCCUPIED_CONFIRMATION_EMAIL,
    COMPLIANCE_EXPIRED_UNOCCUPIED_CONFIRMATION_EMAIL,
    COMPLIANCE_EXPIRED_OCCUPIED_EPC_CONFIRMATION_EMAIL,
    LOCAL_COUNCIL_REGISTRATION_CONFIRMATION_EMAIL,
    LOCAL_COUNCIL_USER_DELETION_EMAIL,
    LOCAL_COUNCIL_USER_DELETION_INFORM_ADMIN_EMAIL,
    LOCAL_COUNCIL_USER_INVITATION_INFORM_ADMIN_EMAIL,
    INCOMPLETE_PROPERTY_REMINDER_EMAIL,
    JOINT_LANDLORD_INVITATION_EMAIL,
    JOINT_LANDLORD_INVITATION_CONFIRMATION_EMAIL,
    JOINT_LANDLORD_INVITATION_NOTIFY_EXISTING_EMAIL,
    JOINT_LANDLORD_INVITATION_EXPIRY_EMAIL,
    JOINT_LANDLORD_INVITATION_CANCELLATION_INVITEE_EMAIL,
    JOINT_LANDLORD_INVITATION_CANCELLATION_CANCELLER_EMAIL,
    JOINT_LANDLORD_INVITATION_CANCELLATION_OTHER_LANDLORD_EMAIL,
    JOINT_LANDLORD_INVITATION_REJECTION_EMAIL,
    JOINT_LANDLORD_INVITATION_ACCEPTED_EMAIL,
    JOINT_LANDLORD_INVITATION_ACCEPTED_OTHER_LANDLORD_EMAIL,
    JOINT_LANDLORD_PROPERTY_UPDATE_NOTIFICATION_EMAIL,
    SWITCH_TO_INDIVIDUAL_CONFIRMATION,
    SWAP_TO_INDIVIDUAL_NUDGE_EMAIL,
    JOINT_LANDLORD_OTHER_LANDLORD_LEFT_NOTIFICATION,
    JOINT_LANDLORD_YOU_LEFT_CONFIRMATION,
    ORGANISATIONAL_LANDLORD_REGISTRATION_CONFIRMATION_EMAIL,
    ORGANISATIONAL_LANDLORD_DEREGISTRATION_CONFIRMATION_EMAIL,
    ORGANISATIONAL_LANDLORD_UPDATE_CONFIRMATION,
    LETTING_AGENT_CANCEL_DELEGATION_LANDLORD_CONFIRMATION_EMAIL,
    LETTING_AGENT_CANCEL_DELEGATION_JOINT_LANDLORD_NOTIFICATION_EMAIL,
    LETTING_AGENT_CANCEL_DELEGATION_LETTING_AGENT_NOTIFICATION_EMAIL,
}
