features:
  overrides-enabled: true
  feature-flags:
    - name: "failover-test-endpoints"
      enabled: true
      expiry-date: "2026-12-31"
    - name: "subject-identifier-page"
      enabled: true
      expiry-date: "2027-03-30"
    - name: "pdjb-939-property-registration-restructure-and-skipping"
      enabled: true
      expiry-date: "2026-12-31"
    - name: "pdjb-939-property-registration-phase-two"
      enabled: true
      expiry-date: "2026-12-31"
    - name: "pdjb-1053-dashboard-nav-link"
      enabled: true
      expiry-date: "2026-12-31"
    - name: "pdjb-1022-delegate-to-letting-agent"
      enabled: true
      expiry-date: "2026-12-31"
    - name: "pdjb-1664-password-benchmark-endpoint"
      enabled: true
      expiry-date: "2026-12-31"
    - name: "pdjb-1040-correspondence-address"
      enabled: true
      expiry-date: "2026-12-31"
    - name: "pdjb-1009-payments"
      enabled: true
      expiry-date: "2026-12-31"

argon2:
  iterations: 2
  memory: 16384
  parallelism: 1
