name: Build and Deploy - Integration
on:
  push:
    branches:
      - main

concurrency:
  group: deploy-integration
  cancel-in-progress: false

jobs:
  build-and-deploy-integration:
    name: Build and Deploy
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      environment: "integration"
      aws-account-id: "794038239680"
    secrets: inherit
